import mongoose from "mongoose";

const siteSettingsSchema = new mongoose.Schema(
  {
    id: { type: String, default: "global", unique: true, index: true },
    company_name: { type: String, default: "Royal Palm Dates" },
    company_short_name: { type: String, default: "RP" },
    company_legal_name: { type: String, default: "Royal Palm Dates SARL" },
    site_code: { type: String, default: "RP-TOZ" },
    country_code: { type: String, default: "TN" },
    logo_url: { type: String, default: null },
    logo_base64: { type: String, default: null },
    primary_color: { type: String, default: "#107754" },
    accent_color: { type: String, default: "#d97706" },
    plant_name: { type: String, default: "Usine Tozeur" },
    plant_address: { type: String, default: null },
    plant_phone: { type: String, default: null },
    plant_email: { type: String, default: null },
    features: {
      receptions_enabled: { type: Boolean, default: true },
      phase2_enabled: { type: Boolean, default: true },
      production_enabled: { type: Boolean, default: true },
      packaging_enabled: { type: Boolean, default: true },
      logistics_enabled: { type: Boolean, default: true },
      purchasing_enabled: { type: Boolean, default: true },
      analytics_enabled: { type: Boolean, default: true },
      stock_enabled: { type: Boolean, default: true },
      supplier_master_enabled: { type: Boolean, default: true },
      materials_master_enabled: { type: Boolean, default: true },
      alerts_enabled: { type: Boolean, default: true },
      sage_enabled: { type: Boolean, default: true },
    },
    default_language: { type: String, default: "fr" },
    currency: { type: String, default: "TND" },
    timezone: { type: String, default: "Africa/Tunis" },
    interface: {
      ui_density: { type: String, default: "comfortable" },
      default_home_tab: { type: String, default: "home" },
      show_kpi_cards: { type: Boolean, default: true },
      enable_animations: { type: Boolean, default: true },
      rows_per_page: { type: Number, default: 25 },
      date_format: { type: String, default: "dd/MM/yyyy" },
      time_format: { type: String, default: "24h" },
    },
    operations: {
      allow_spontaneous_reception: { type: Boolean, default: true },
      require_purchase_order_for_reception: { type: Boolean, default: false },
      require_vehicle_number_on_reception: { type: Boolean, default: true },
      auto_assign_material_from_po: { type: Boolean, default: true },
      shift_model: { type: String, default: "2x8" },
      shift_handover_notes_required: { type: Boolean, default: true },
      production_auto_start_next_step: { type: Boolean, default: false },
      packaging_requires_final_scan: { type: Boolean, default: true },
      allow_negative_stock: { type: Boolean, default: false },
      stock_reservation_enabled: { type: Boolean, default: true },
    },
    quality: {
      qc_hold_on_reception: { type: Boolean, default: true },
      supplier_lot_required: { type: Boolean, default: true },
      origin_tracking_required: { type: Boolean, default: true },
      expiry_tracking_mode: { type: String, default: "recommended" },
      lot_release_requires_qc: { type: Boolean, default: true },
      default_qc_sample_percent: { type: Number, default: 10 },
      deviation_escalation_hours: { type: Number, default: 4 },
      recall_coordinator: { type: String, default: null },
      allergen_tracking_enabled: { type: Boolean, default: false },
      cold_chain_monitoring_enabled: { type: Boolean, default: false },
    },
    documents: {
      reception_prefix: { type: String, default: "REC" },
      purchase_order_prefix: { type: String, default: "PO" },
      production_order_prefix: { type: String, default: "OF" },
      packaging_order_prefix: { type: String, default: "PKG" },
      shipment_prefix: { type: String, default: "EXP" },
      pallet_prefix: { type: String, default: "PAL" },
      lot_prefix: { type: String, default: "LOT" },
      numbering_padding: { type: Number, default: 5 },
      show_logo_on_prints: { type: Boolean, default: true },
      print_language: { type: String, default: "fr" },
      certificate_signatory: { type: String, default: null },
      report_footer: { type: String, default: null },
    },
    notifications: {
      browser_notifications_enabled: { type: Boolean, default: true },
      email_notifications_enabled: { type: Boolean, default: false },
      low_stock_alert_enabled: { type: Boolean, default: true },
      expiry_alert_enabled: { type: Boolean, default: true },
      expiry_alert_days: { type: Number, default: 30 },
      qc_alert_enabled: { type: Boolean, default: true },
      production_delay_alert_enabled: { type: Boolean, default: true },
      daily_digest_enabled: { type: Boolean, default: true },
      digest_hour: { type: String, default: "07:30" },
      escalation_after_minutes: { type: Number, default: 60 },
    },
    integrations: {
      scale_capture_enabled: { type: Boolean, default: false },
      barcode_scanner_enabled: { type: Boolean, default: true },
      label_printer_enabled: { type: Boolean, default: true },
      qr_labels_enabled: { type: Boolean, default: true },
      erp_sync_mode: { type: String, default: "manual" },
      maintenance_sync_enabled: { type: Boolean, default: false },
      ai_assistant_enabled: { type: Boolean, default: false },
      ai_vision_sorting_enabled: { type: Boolean, default: false },
      api_webhooks_enabled: { type: Boolean, default: false },
      transport_tracking_enabled: { type: Boolean, default: true },
      google_maps_api_key: { type: String, default: null },
      maps_default_zoom: { type: Number, default: 10 },
      tracking_refresh_seconds: { type: Number, default: 30 },
      mission_eta_alert_minutes: { type: Number, default: 30 },
    },
    p2p: {
      enable_minimum_quotes_rule: { type: Boolean, default: true },
      rfq_minimum_quote_count: { type: Number, default: 3 },
      rfq_quote_threshold_tnd: { type: Number, default: 1000 },
      require_purchase_order_for_goods_receipt: { type: Boolean, default: false },
      default_invoice_tolerance_pct: { type: Number, default: 3 },
      require_goods_receipt_for_payment: { type: Boolean, default: false },
      sites: {
        ROYALE_PALM: {
          code: { type: String, default: "ROYALE_PALM" },
          name: { type: String, default: "Royale Palm Tunisia" },
          bio_certification_required: { type: Boolean, default: false },
          phytosanitary_required: { type: Boolean, default: false },
          lot_traceability_required: { type: Boolean, default: false },
          dluo_required: { type: Boolean, default: false },
          fds_required: { type: Boolean, default: false },
          forex_enabled: { type: Boolean, default: true },
          systematic_quarantine: { type: Boolean, default: false },
          cert_alert_days: { type: [Number], default: [60, 30] },
        },
        ECODATTE: {
          code: { type: String, default: "ECODATTE" },
          name: { type: String, default: "EcoDatte" },
          bio_certification_required: { type: Boolean, default: true },
          phytosanitary_required: { type: Boolean, default: true },
          lot_traceability_required: { type: Boolean, default: false },
          dluo_required: { type: Boolean, default: false },
          fds_required: { type: Boolean, default: false },
          forex_enabled: { type: Boolean, default: false },
          systematic_quarantine: { type: Boolean, default: false },
          cert_alert_days: { type: [Number], default: [60, 30] },
        },
        BIOSCHA: {
          code: { type: String, default: "BIOSCHA" },
          name: { type: String, default: "Bioscha" },
          bio_certification_required: { type: Boolean, default: false },
          phytosanitary_required: { type: Boolean, default: false },
          lot_traceability_required: { type: Boolean, default: true },
          dluo_required: { type: Boolean, default: true },
          fds_required: { type: Boolean, default: true },
          forex_enabled: { type: Boolean, default: false },
          systematic_quarantine: { type: Boolean, default: true },
          cert_alert_days: { type: [Number], default: [60, 30] },
        },
      },
      approval_matrix: {
        type: [
          {
            level: { type: String, required: true },
            threshold_gte: { type: Number, required: true },
            label: { type: String, required: true },
          },
        ],
        default: [
          { level: "dept_manager", threshold_gte: 0, label: "Responsable département" },
          { level: "purchasing_manager", threshold_gte: 1000, label: "Responsable Achats" },
          { level: "daf", threshold_gte: 10000, label: "DAF" },
          { level: "general_direction", threshold_gte: 50000, label: "Direction Générale" },
        ],
      },
    },
    updated_by: { type: String, default: null },
    updated_at: { type: String, default: () => new Date().toISOString() },
  },
  {
    collection: "site_settings",
    versionKey: false,
  },
);

export const SiteSettingsModel: any =
  (mongoose.models as any).site_settings ||
  mongoose.model("site_settings", siteSettingsSchema, "site_settings");
